### ISSUE TITLE
classify-consensus-blast: expose num_threads

### ISSUE THREAD

**Issue by nbokulich** [qiime2/q2-feature-classifier#155] opened 2020-01-21 17:17 UTC
**Improvement Description**
Expose num_threads to enable parallelization in classify-consensus-blast

**Current Behavior**
num_threads is not exposed.

**Proposed Behavior**
Expose it.

**Comment by splaisan** [comment] 2020-01-29 08:58
please someone implement this, our jobs are taking forever against SILVA due to blast being single threaded. I would do the edit myself if I knew enough of python (sob)

**Comment by gregcaporaso** [comment] 2020-01-29 18:15
Note: @cherman2 is going to work on this issue.

**Comment by cherman2** [comment] 2020-02-19 15:55
I see that in past code, there was a num_thread that was set to 1 (num_threads: str=1), in the current version the numThread variable does not exist. I can see in the history that it was removed because "The 'num_threads' parameter had no effect with the mode that 'blastn' is invoked in." Should num_threads be reimplemented to equal 1, and be exposed, or should num_threads be an amount that is decided by the user? If so, what is the max amount of threads the code should allow?
The past code: [https://github.com/qiime2/q2-feature-classifier/commit/9a88406a735887443f67c864530af8d8644cdf74#diff-09b8f70df4e6b546aa7e9361837f99a8](url)

**Comment by thermokarst** [comment] 2020-02-19 16:17
Awesome, thanks for the sleuthing, @cherman2! 🔍 

Based on the issue/PR you linked to (#77), it is safe to assume that _this_ issue (#155) is not actually something that can be accomplished (sorry @splaisan, our hands are tied), since `-num_threads` is ignored when the `-subject` parameter is supplied to the `blastn` tool. 

What do you think about pivoting this issue and turning it into a documentation issue? Specifically, would you be able to add a comment to the source code where the `classify_consensus_blast` function is defined, explaining why `-num_threads` isn't exposed? Please include a link to issue #77, if possible. My rationale for this comment/documentation request is simple: hopefully it will prevent us from retreading over this ground (#155, #77) again!

Please let me know if you have any questions, or if I can clarify anything for you. Thanks!

PS - I confirmed that blastn 2.6.0 (which we are currently using in q2-feature-classifier) still emits this warning

**Comment by cherman2** [comment] 2020-02-19 22:07
@gregcaporaso and @thermokarst. I created a fork of _blast.py with my proposed documentation of the issue. Let me know if there is anything else I need to do on my end!

**Comment by thermokarst** [comment] 2020-02-19 22:10
Thanks @cherman2!

Please open up a [GitHub Pull Request](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request) ([second ref](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork)) to get your changes ready for review.

Thanks!

**Comment by cherman2** [comment] 2020-02-19 22:18
Done! @thermokarst

**Comment by MaestSi** [comment] 2020-02-28 16:06
Hi, is there any chance you could wrap makeblastdb, so that classify-consensus-blast first creates a blast-indexed database starting from the fasta file included in the FeatureData[Sequence] artifact, and then performs the alignment (specifying -db instead of -subject), so that it can be run with multi-threading?
Thanks,
Simone

**Comment by thermokarst** [comment] 2020-03-17 18:42
Closed in #157

**Closed by thermokarst** 2020-03-17 18:42 UTC
Labels: diff:1|beginner, good first issue, help wanted, scope:0|this-project, src:forum, time:1|short
