### ISSUE TITLE
 pop from empty list error when taxonomy label not complete

### ISSUE THREAD

**Issue by ssavvi** [qiime2/q2-feature-classifier#168] opened 2021-01-08 21:56 UTC
qiime feature-classifier classify-sklearn --i-classifier SILVA_132_QIIME_release/silva_132_99_16S_a515F-806R-classifier_2020_6.qza --i-reads dada2/rep-seqs.qza --o-classification taxonomy/taxonomy.qza

Plugin error from feature-classifier:

pop from empty list

Debug info has been saved to /tmp/qiime2-q2cli-err-n_wtmsqa.log

can some one help with the above error please?

**Comment by andrewsanchez** [comment] 2021-01-08 23:37
Hi, @ssavvi!  There's no need to open a new issue in this case.  You can leave further comments on #93 if you'd like.  Thanks!   (duplicate of #93)

**Closed** 2021-01-08 23:38 UTC
