### ISSUE TITLE
Missing parameter descriptions in classify-sklearn

### ISSUE THREAD

**Issue by ElDeveloper** [qiime2/q2-feature-classifier#85] opened 2017-08-22 07:17 UTC
There's no documentation for the following parameters:

```
  --i-reads PATH                  Artifact: FeatureData[Sequence]  [required]
  --i-classifier PATH             Artifact: TaxonomicClassifier  [required]
  --p-chunk-size INTEGER          [default: 262144]
  --p-n-jobs INTEGER              [default: 1]
  --p-pre-dispatch TEXT           [default: 2*n_jobs]
```

**Comment by thermokarst** [comment] 2017-08-22 13:03
Possibly a dupe of #46 (or at least related) - thanks @ElDeveloper

**Comment by ElDeveloper** [comment] 2017-09-11 18:00
If this can't be fixed right now, would it be possible to get a description of each of these flags n-jobs seems straight forward but I don't know what pre-dispatch or chunk-size mean. And more importantly how should I tweak these.

**Comment by jairideout** [comment] 2017-09-11 18:14
I pinged @BenKaehler to see if he can work on this for 2017.9. Thanks!

**Closed** 2017-09-21 03:23 UTC
Labels: bug
